### ISSUE TITLE
ImportError: No module named reportlab.pdfgen.canvas

### ISSUE THREAD

**Issue by mturley** [bcbnz/pylabels#1]
Hi there,

I'm excited to switch from my crappy PHP Imagemagick label code to pylabels.  However, I get an error when trying the basic.py demo script.

I installed pylabels on my Ubuntu machine as follows:

```
$ sudo apt-get install build-essential libfreetype6-dev python-dev python-imaging python-setuptools
$ sudo easy_install pylabels
```

I then cloned the pylabels git repo and tried `python demos/basic.py` and this is what I get:

```
Traceback (most recent call last):
  File "basic.py", line 17, in <module>
    import labels
  File "/usr/local/lib/python2.7/dist-packages/pylabels-1.0.0-py2.7.egg/labels/__init__.py", line 17, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pylabels-1.0.0-py2.7.egg/labels/sheet.py", line 17, in <module>
ImportError: No module named reportlab.pdfgen.canvas
```

I tried the same thing on my Mac, following the Mac setup instructions for reportlab (reportlab was preinstalled for my Ubuntu machine), and I get the same error.  I know ReportLab is installed fine, but do I need to install something more for pdfgen.canvas to be available?

**Comment by ANTHONY-OLEVESTER** [comment]
i am facinge this issue in my python environment I tried reinstalling and downgrading it and also loggining in with my username and password to the original website to download but to no avail this is working in my project
![image](https://github.com/bcbnz/pylabels/assets/47980189/bfb9b15e-fb51-4b45-8ef6-0354122515ef)
