### ISSUE TITLE
How to create multiline text using `pylabels`

### ISSUE THREAD

**Issue by noppGithub** [bcbnz/pylabels#20]
I want to create labels with the following contents.
Is it possible to do ?
```python
52/3 Avenue road,
Chumpo district,
Lamgo province 19456
                                          <John Saverilo>
```

**Comment by command-tab** [comment]
You can use a loop with an incrementing vertical offset to draw each line as its own string -- something like this:

```python
import labels
from reportlab.graphics import shapes

FONT_SIZE = 12
POINT_AS_1_MM = 2.83465
PAPER_WIDTH_MM = 215.9
PAPER_HEIGHT_MM = 279.4
ROW_COUNT = 7
COL_COUNT = 7
LABEL_WIDTH_MM = 25.4
LABEL_HEIGHT_MM = 38.1

specs = labels.Specification(
    PAPER_WIDTH_MM,
    PAPER_HEIGHT_MM,
    ROW_COUNT,
    COL_COUNT,
    LABEL_WIDTH_MM,
    LABEL_HEIGHT_MM,
    corner_radius=3,
    top_margin=6.35,
    right_margin=9.525,
    bottom_margin=6.35,
    left_margin=9.525
)

def draw_label(label, width, height, value):
    lines = value.split('\n')
    x_offset_mm = 5
    y_offset_mm = 6
    for line_number, line in enumerate(lines, start=1):
        line_string = shapes.String(
            x=x_offset_mm * POINT_AS_1_MM,
            y=((label_height_mm * POINT_AS_1_MM) - (FONT_SIZE * line_number)) - (y_offset_mm * POINT_AS_1_MM),
            text=line,
            fontName='Courier',
            fontSize=FONT_SIZE,
            textAnchor='start'
        )
        label.add(line_string)

sheet = labels.Sheet(specs, draw_label, border=False)
```

(No promises this code executes without error as I pieced it together from another project, but I hope you get the idea.)

**Comment by noppGithub** [comment]
@command-tab Thank you so much, now it's working perfectly with your guide, however may I ask what is `POINT_AS_1_MM` ?

**Comment by command-tab** [comment]
Excellent! Glad that helped.

`POINT_AS_1_MM` is just a constant that defines how many [points](https://en.wikipedia.org/wiki/Point_(typography)) 1 millimeter is so that we can think and code in millimeters instead of points. If you're more comfortable working directly in points, you can certainly omit the constant definition and associated math.

**Comment by noppGithub** [comment]
@command-tab Thanks alot I learn new thing(the point vs mm) from you agian <3

**Comment by noppGithub** [comment]
Resolution is working and tested
