### ISSUE TITLE
Question about barcodes

### ISSUE THREAD

**Issue by nuin** [bcbnz/pylabels#4]
Hi

I really like this package and helped me get me out of many troubles. But now we are trying to include a barcode into the labels (4 x 8 in a letter sized page). We are using a pure Reportlab barcode generator with

```
bc = Code128(obj, barWidth=0.01*mm, ratio=3, barHeight=bh, quiet=0)
```

where obj is the string for the barcode. I have been trying different things in Reportlab to add the barcode to the label, with no success. I must admit that I don't know Reportlab enough, and I am checking your code looking for clues.

Any help is appreciated.

**Comment by mturley** [comment]
Hey there,

I'm not the maintainer of this project, but I've recently used it in a barcode label generator application and I may be able to help.  I don't know if there's a better way to do this, but I used the reportlab.graphics.barcode package to generate the barcode as an image and then added the image to my labels.  Now, I couldn't figure out how to get the PIL image-in-memory to be added directly to the label, and I still want to improve this code, but I just save it out to a file for now, and add it to the label by filename.  That seems to work fine.  Here's the code I used (where str is the string for the barcode):

    from reportlab.graphics import barcode
    
    barcode_image_raw = barcode.createBarcodeImageInMemory('Code128', value=str, width=400, height=120)
    barcode_image = PIL.Image.open(StringIO(barcode_image_raw))
    barcode_image.save("tmp-barcode.png", 'png')

    // later on (after declaring barcode_x, barcode_y, barcode_width and barcode_height)
    label.add(shapes.Image(barcode_x, barcode_y, barcode_width, barcode_height, "tmp-barcode.png")

Not necessarily the best approach, but it's meeting my needs.  Hope this helps!

**Comment by mturley** [comment]
Note also that when I generated the barcode image using certain width and height values, then added the resulting image to the label using the same width and height values, the barcode image came out a little fuzzy and wouldn't scan.  I had to generate the image much larger, and then add it to the label at about about 1/4 the size.  Then the barcode came out nice and sharp and scanned just fine.

Yet again, this was a lot of trial-and-error and I'd love to come back and improve the code, but since it works, I haven't really been prioritizing that.

**Comment by nuin** [comment]
Thanks @mturley, that was one avenue that I contemplated doing, it should be good enough to my needs. I already generate the label pages with the actual string of the barcode, and that should work fine for me.

Thanks again.

**Comment by nuin** [comment]
It worked like a charm @mturley. Thanks a lot.

**Comment by mturley** [comment]
Happy I could help!

**Comment by hiousi** [comment]
Closed but might help:

```
from reportlab.graphics.barcode import createBarcodeDrawing
bcd = createBarcodeDrawing('Code128', value='TEXT128')
label.add(bcd)
```

**Comment by phoebebright** [comment]
Here is my code for adding a qrcode to a label in case it helps anyone::

    # spec for avery J8563 - 7 x 2
    specs = labels.Specification(210, 297, 2, 7, 99.1, 38.1, corner_radius=2, top_margin=15.15, bottom_margin=15.15)
    
    
    # Create the sheet.
    sheet = labels.Sheet(specs, draw_label, border=False)
    
    # add labels
    for item in my_list_of_items:
        sheet.add_label(item)
    
    
    # Save the file and we are done.
    sheet.save(self.output_filepath
    
    
    def draw_label(label, w, h, obj):
        # Just convert the object to a string and print this at the bottom left of
        # the label.
        offset = 78
    
        label.add(shapes.String(2, h - 14, str(obj.event.name), fontName="TitilliumWeb", fontSize=11))
        label.add(shapes.String(w - 2, h - 14, obj.entry.test_date.strftime("%d%b%y"), fontName="TitilliumWeb", fontSize=11,
                                textAnchor="end"))
        ...
    
        d = self.get_qr_drawing(obj.url)
        label.add(d)
    
    def get_qr_drawing(self, url):
    
    
        # Create the qrcode from an image
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer)
        c.setFillColor(white)
    
        # bar level is measure of extra bits added to improve chances of decoding
        qrw = QrCodeWidget(url, barLevel="M")
        b = qrw.getBounds()
    
        w = b[2] - b[0]
        h = b[3] - b[1]
    
        d = Drawing(w, h, transform=[70. / w, 0, 0, 70. / h, 0, 0])
        d.add(Rect(0, 0, w, h, fillColor=white))
    
        d.add(qrw)
    
        return d

**Comment by sjlongland** [comment]
Wondered about this myself.  I tried @phoebebright 's code, but it's about 10% syntax errors and 30% missing (lots of undeclared imports, I have no idea where the symbols being used are imported from).

I see Pull Request #19 pretty much does exactly what I'm after using the features built into `reportlab`… looks like with a little adaption it could do linear barcodes like Code128 as well.

**Comment by need4swede** [comment]
> Closed but might help:
> 
> ```
> from reportlab.graphics.barcode import createBarcodeDrawing
> bcd = createBarcodeDrawing('Code128', value='TEXT128')
> label.add(bcd)
> ```

Thanks a lot for this! How would you do this with unique labels? This makes all my labels have the same barcodes

**Comment by nuin** [comment]
It's the `value` parameter that needs to be changed

**Comment by need4swede** [comment]
I tried that; created a whole new variable (bcd_2) with a new value, and used `label.add(bcd_2)`, but it just writes both barcodes on top of each other on the two different labels on the sheet.

I must be doing something wrong here. 

```
import labels
from reportlab.graphics import shapes
from reportlab.graphics.barcode import createBarcodeDrawing
bcd = createBarcodeDrawing('Code128', value='BARONE', width=150, height=20)
bcd_2 = createBarcodeDrawing('Code128', value='BARTWO', width=150, height=20)

PADDING = 1
specs = labels.Specification(
    215.9, 279.4, 3, 10, 64, 25.4, corner_radius=2,
    left_margin=5, right_margin=5, top_margin=13,
    left_padding=5.5, right_padding=PADDING, top_padding=PADDING,
    bottom_padding=9,
    row_gap=0)

def draw_label(label, width, height, obj):
    label.add(shapes.String(width / 4, height / 2, str(obj), fontName="Helvetica", fontSize=20))
    label.add(bcd)
    label.add(bcd_2)

# Create the sheet.
sheet = labels.Sheet(specs, draw_label, border=True)

# Add a couple of labels.
sheet.add_label('label1')
sheet.add_label('label2')


# Save the file and we are done.
sheet.save('labels.pdf')
print("{0:d} label(s) output on {1:d} page(s).".format(sheet.label_count, sheet.page_count))
```

Outcome:

The labels are actually the two barcodes combined, but the label text is unique.

<img width="759" alt="Screen Shot 2022-09-07 at 16 10 27" src="https://user-images.githubusercontent.com/57847545/188998947-efd1deae-7352-4f61-8913-85ed99aa6e18.png">

**Comment by sjlongland** [comment]
I think I know what you're doing wrong… you're creating the barcodes globally, then adding the same to barcodes to _every_ label.

```python
import labels
from reportlab.graphics import shapes
from reportlab.graphics.barcode import createBarcodeDrawing

PADDING = 1
specs = labels.Specification(
    215.9, 279.4, 3, 10, 64, 25.4, corner_radius=2,
    left_margin=5, right_margin=5, top_margin=13,
    left_padding=5.5, right_padding=PADDING, top_padding=PADDING,
    bottom_padding=9,
    row_gap=0)

def draw_label(label, width, height, obj):
    (labelstr, barcodestr) = obj
    label.add(shapes.String(width / 4, height / 2, labelstr, fontName="Helvetica", fontSize=20))
    label.add(createBarcodeDrawing('Code128', value=barcodestr, width=150, height=20))


# Create the sheet.
sheet = labels.Sheet(specs, draw_label, border=True)

# Add a couple of labels.
sheet.add_label(('label1', 'BARONE',))
sheet.add_label(('label2', 'BARTWO',))


# Save the file and we are done.
sheet.save('labels.pdf')
print("{0:d} label(s) output on {1:d} page(s).".format(sheet.label_count, sheet.page_count))
```

Not tested, but that will possibly do what you're after.

**Comment by need4swede** [comment]
@sjlongland 
Wow, you're so right. Makes perfect sense now - thank you so much for your help!!

**Comment by neva42** [comment]
@sjlongland , thanks for your example, it worked perfectly and now I can understand better how it works.
One question: when using createBarcodeDrawing on label.add, how can I specify the position where it is created? shapes.String have positional parameters, but I could not find out how to specify the position (x,y) where the barcord should be drawn! If you have any clues, I really appreciate. Thanks!

**Comment by sjlongland** [comment]
> @sjlongland , thanks for your example, it worked perfectly and now I can understand better how it works. One question: when using createBarcodeDrawing on label.add, how can I specify the position where it is created? shapes.String have positional parameters, but I could not find out how to specify the position (x,y) where the barcord should be drawn! If you have any clues, I really appreciate. Thanks!

That I'm not sure of.  It's literally been a couple of years since I last looked at this so I'd have to revise what I did, but my hunch would be to look at the `createBarcodeDrawing()` or `label.add()` calls to see if there's positional parameters there.

**Comment by DejanLe** [comment]
Hello everyone this code works for me. Example how to move barcode anywhere

def draw_label(label, width, height, obj):
    label.add(example_barcode)

cpecs=labels.Specification(210,297,1,4,210,70,corner_radius=1)
sheet=labels.Sheet(specs, draw_label, border=True)
example_value= "1234"
example_barcode= createBarcodeDrawing("code128",value=example_value)
barcode_x = 85
barcode_y=115
barcode_width=100
barcode_height=20
example_barcode.translate(barcode_x ,barcode_y)
sheet.add_label(example_barcode)
sheet.save("example.pdf")

**Comment by sjlongland** [comment]
> Hello everyone this code works for me. Example how to move barcode anywhere

Please remember to enclose code examples in \`\`\` blocks, otherwise you get an un-indented mess that Python will reject as being invalid.
