### ISSUE TITLE
Python 3.6 problem with labels as module name

### ISSUE THREAD

**Issue by barrar** [bcbnz/pylabels#8]
```
import labels
from reportlab.graphics import shapes
specs = labels.Specification(210, 297, 2, 8, 90, 25, corner_radius=2)

```

This code fails, resulting in:

`module 'labels' has no attribute 'Specification'
`

Renaming Python36\Lib\site-packages\labels to \site-packages\pylabels solves all problems. Now this code works: 

```
import pylabels
from reportlab.graphics import shapes
specs = pylabels.Specification(210, 297, 2, 8, 90, 25, corner_radius=2)

```

**Comment by bcbnz** [comment]
It works fine for me on Python 3.6. It sounds like you've got something else installed on your system which has the same name, or maybe you have a file in the current directory called labels.py.

Use

```python
import labels
print(labels.__file__)
```

to show you where the module is getting imported from.
